dictionaries = ["ru", "en_us"]

# –º–Ω–µ –Ω–µ–º–Ω–æ–≥–æ –ª–µ–Ω—å –¥–æ–±–∞–≤–ª—è—Ç—å —Å—é–¥–∞ –≤—Å—ë, —á—Ç–æ –Ω–µ –¥–æ–ª–∂–µ–Ω –ø–æ–º–µ—á–∞—Ç—å codebook...
words = [
    "arctg",
    "cov",
    "liquidus",
    "ognevny",
    "radic",
    "–ê–≤—Ä–∞–∞–º–∏—á–µ—Å–∫–∏–µ",
    "–ê–≤—Å—Ç—Ä–æ",
    "–ê–∫–º–∞–µ–≤–∞",
    "–ê–ª–∞–º–±–µ—Ä–∞",
    "–∞–Ω–Ω–∏–≥–∏–ª–∏—Ä–æ–≤–∞–Ω—ã",
    "–∞–Ω—Ç–∏–∫—É–ª—å—Ç—É—Ä–∞",
    "–∞–Ω—Ç–∏–æ—Ä–¥—ã–Ω—Å–∫–æ–≥–æ",
    "–∞–Ω—Ç–∏—Ä–µ—Ñ–æ—Ä–º–µ–Ω–Ω—É—é",
    "–∞–Ω—Ç–∏—Ñ—Ä–∞–Ω—Ü—É–∑—Å–∫—É—é",
    "–ê—Ä–∞–∫—á–µ–µ–≤–∞",
    "–ê—Ä—Ç–æ–±–æ–ª–µ–≤—Å–∫–∏–π",
    "–ê—Ä—Ç–æ–±–æ–ª–µ–≤—Å–∫–æ–≥–æ",
    "–ê—Ä—Ç–æ–±–æ–ª–µ–≤—Å–∫–æ–º—É",
    "–∞—Ä—Ö–∏—Ç–∏–ø",
    "–ê—Å—Å—É—Ä–∞",
    "–ê—Å—Å—É—Ä—É",
    "–ê—Ç–∞–±–µ–∫–æ–≤",
    "–ê—Ç—Ç–∏–ª—ã",
    "–∞—É—Å—Ç–µ–Ω–∏—Ç–Ω–æ–≥–æ",
    "–∞—É—Å—Ç–µ–Ω–∏—Ç–Ω—É—é",
    "–ë–∞–π–µ—Å–∞",
    "–ë–∞—Ä–∏—Ü–µ–Ω—Ç—Ä",
    "–±–∞—Ä–∏—Ü–µ–Ω—Ç—Ä",
    "–±–∞—Ä–∏—Ü–µ–Ω—Ç—Ä–æ–º",
    "–ë–∞—Ç—ã–π",
    "–ë–∞—Ç—ã—è",
    "–±–µ–∑–¥–∏—Ñ—Ñ—É–∑–∏–æ–Ω–Ω–æ",
    "–±–µ–∑–¥–∏—Ñ—Ñ—É–∑–∏–æ–Ω–Ω–æ–≥–æ",
    "–±–µ–∑–¥–∏—Ñ—Ñ—É–∑–∏–æ–Ω–Ω–æ–º—É",
    "–±–µ–∑—Ä–µ–ª–∏–≥–∏–æ–∑–Ω–∞",
    "–ë–µ–∑—É",
    "–±–µ–∑—É–≥–ª–µ—Ä–æ–¥–∏—Å—Ç–∞—è",
    "–ë–µ–π–Ω–∏—Ç–Ω–æ–µ",
    "–ë–µ–ª–æ–æ–∑—ë—Ä—Å–∫",
    "–ë–µ—Ä–¥—è–µ–≤",
    "–±–∏–∫—Ä–∏—Å—Ç–∞–ª–ª",
    "–ë–∏–ª—å–±–µ—Ä—Ç",
    "–ë–∏—Ä–æ–Ω",
    "–ë–æ–±—Ä–∏–Ω—Å–∫–∏–π",
    "–ë–æ–π–ª—é",
    "–±–æ–ª",
    "–ë–æ–Ω–¥–∞—Ä–µ–Ω–∫–æ–≤", # üò°
    "–ë–æ—á–≤–∞—Ä–∞",
    "–±—Ä–∏–Ω–µ–ª–ª—å",
    "–ë—Ä–∏–Ω–µ–ª–ª—é",
    "–±—É–ª–≥–∞—Ä–∞–º–∏",
    "–±—É–ª–ª–∏–Ω–≥",
    "–±—É–Ω—Ç–∞—Ä–Ω—ã—Ö",
    "–ë—é—Ñ—Ñ–æ–Ω",
    "–í–∞–∞–ª—å—Å–æ–≤–∞",
    "–≤–∞–∫—É—É–º–µ—Ç—Ä–∏—á–µ—Å–∫–æ–µ",
    "–í–∞—Ä—ë–Ω–æ–∫",
    "–í–µ–π–±—É–ª–ª–∞",
    "–í–µ–Ω–∞–Ω–∞",
    "–í–µ—Ä–µ—â–∞–≥–∏–Ω–∞",
    "–í–µ—Ä–µ—â–∞–≥–∏–Ω—É",
    "–≤–∑–∞–∏–º–Ω–æ–ø–µ—Ä–ø–µ–Ω–¥–∏–∫—É–ª—è—Ä–Ω—ã—Ö",
    "–≤–∑–∞–∏–º–æ–¥–∏—Å–ª",
    "–í–∏–µ—Ç–∞",
    "–≤–∏–∫–∫–µ—Ä—Å",
    "–í–∏–∫–∫–µ—Ä—Å—É",
    "–í–∏–Ω–æ–≥—Ä–∞–¥–æ–≤–∞",
    "–í–∏—Å–∫–µ—Ä—ã",
    "–í–∏—Ç–≤–æ—Ä—Ç–∞",
    "–≤–Ω–µ–≤–ø–∏—Å–∞–Ω–Ω—ã–π",
    "–≤–Ω–µ–≤–ø–∏—Å–∞–Ω–Ω—ã—Ö",
    "–í–Ω–µ—Ü–µ–Ω—Ç—Ä–µ–Ω–Ω–æ–µ",
    "–≤–Ω–µ—Ü–µ–Ω—Ç—Ä–µ–Ω–Ω–æ–º",
    "–í–Ω–µ—Ü–µ–Ω—Ç—Ä–µ–Ω–Ω—ã–º",
    "–í—Ä–æ–Ω—Å–∫–æ–≥–æ",
    "–≤—Ç–æ—Ä–æ–π–≤–∏–¥",
    "–≤—ã—Å–æ–∫–æ—É–≥–ª–µ—Ä–æ–¥–∏—Å—Ç—ã—Ö",
    "–≤—ã—Å–æ–∫–æ—É–≥–ª–æ–≤–∞—è",
    "–í—ã—à–µ—Å–ª–∞–≤–∞",
    "–ì–∞–ø–æ–Ω–∞",
    "–≥–µ–Ω–¥–µ—Ä–Ω—ã–µ",
    "–ì–µ—Ä–æ–Ω–∞",
    "–ì–ª–∏–≤–µ–Ω–∫–æ",
    "–ì–ª–∏–Ω—Å–∫–æ–π",
    "–ì–æ–¥—É–Ω–æ–≤",
    "–ì–æ–¥—É–Ω–æ–≤–∞",
    "–ì–æ–ª–æ–≤–∏–Ω",
    "–≥–æ–º–æ–≥–µ–Ω–Ω–∏–∑–∞—Ü–∏–æ–Ω–Ω—ã–π",
    "–ì–æ–º–æ–≥–µ–Ω–Ω–∏–∑–∞—Ü–∏–æ–Ω–Ω—ã–π",
    "–ì–æ—Ä–Ω–µ—Ä–∞",
    "–≥–æ—Ä—è—á–µ–∫–∞—Ç–∞–Ω–Ω–æ–π",
    "–≥—Ä–∞—Ñ–∏—Ç–µ–∑–∏—Ä—É—é—â–µ–º—É",
    "–≥—Ä–∞—Ñ–æ",
    "–ì—É–Ω–æ–≤",
    "–ì—É–Ω—ã",
    "–ì—É—á–∫–æ–≤",
    "–î–∞–ª—é",
    "–î–∞—Ä–¥–∞–Ω–µ–ª–ª—ã",
    "–¥–≤—É—Ç–∞–≤—Ä—à–≤–µ–ª–ª–µ—Ä",
    "–î–≤—É—Ö–æ–ø–æ—Ä–Ω–∞—è",
    "–¥–≤—É—Ö–æ–ø–æ—Ä–Ω–∞—è",
    "–î–≤—É—Ö—Å—Ç–µ—Ä–∂–Ω–µ–≤–∞—è",
    "–¥–µ–ø–ª–∞–Ω–∞—Ü–∏–∏",
    "–¥–µ–ø–ª–∞–Ω–∏—Ä—É–µ—Ç",
    "–¥–µ—Ä",
    "–¥–µ—Ç–µ—Ä–º–µ–Ω–∏—Ä–æ–≤–∞–Ω–Ω—ã–µ",
    "–¥–µ—Ç–æ–≤–æ–∂–¥–µ–Ω–∏–µ",
    "–¥–µ—Ü–∏–ª–∏",
    "–î–∂–µ–≤–æ–Ω—Å",
    "–¥–∏–∞–≥—Ä—Ä–∞—Å—Ç",
    "–¥–∏–∞–≥—Ä—Å–∂–∞—Ç",
    "–¥–∏–∞–≥—Ä—É—Å–ª",
    "–¥–∏–∞–≥—Ä—á—É–≥—É–Ω",
    "–î–∏—Ä–∞",
    "–¥–∏—Ñ—Ñ—É–∑–∏–æ–Ω–Ω–æ",
    "–î–æ—Ä–µ–∫—Ä–∏—Å—Ç–∞–ª–ª–∏–∑–∞—Ü–∏–æ–Ω–Ω—ã–π",
    "–¥–æ—ç–≤—Ç–µ–∫—Ç–∏—á–µ—Å–∫–∏–µ",
    "–¥–æ—ç–≤—Ç–µ–∫—Ç–∏—á–µ—Å–∫–∏–π",
    "–¥–æ—ç–≤—Ç–µ–∫—Ç–∏—á–µ—Å–∫–∏—Ö",
    "–¥–æ—ç–≤—Ç–µ–∫—Ç–æ–∏–¥–Ω–æ–π",
    "–¥–æ—ç–≤—Ç–µ–∫—Ç–æ–∏–¥–Ω—ã–µ",
    "–¥–æ—ç–≤—Ç–µ–∫—Ç–æ–∏–¥–Ω—ã—Ö",
    "–î—é—Ä–∫–≥–µ–π–º",
    "–ñ—É—Ä–∞–≤—Å–∫–æ–≥–æ",
    "–ó–∞—Ä–æ–¥–æ–≤",
    "–ó–∞—Ä–æ–¥–æ–≤–∞",
    "–∑–∞—Ä–æ–∂–¥–∫—Ä–∏—Å—Ç",
    "–∑–∞—ç–≤—Ç–µ–∫—Ç–∏—á–µ—Å–∫–∏–µ",
    "–∑–∞—ç–≤—Ç–µ–∫—Ç–∏—á–µ—Å–∫–∏–π",
    "–∑–∞—ç–≤—Ç–µ–∫—Ç–∏—á–µ—Å–∫–∏—Ö",
    "–∑–∞—ç–≤—Ç–µ–∫—Ç–æ–∏–¥–Ω–∞—è",
    "–∑–∞—ç–≤—Ç–µ–∫—Ç–æ–∏–¥–Ω–æ–π",
    "–∑–∞—ç–≤—Ç–µ–∫—Ç–æ–∏–¥–Ω—ã–µ",
    "–∑–∞—ç–≤—Ç–µ–∫—Ç–æ–∏–¥–Ω—ã—Ö",
    "–ó–∏–≥–º—É–Ω–¥—É",
    "–ó–∏–Ω–æ–≤—å–µ–≤–∞",
    "–∑–æ–¥—á–∏–∏",
    "–ò–∑–≤–æ—Ä—Å–∫",
    "–∏–∑–≥–∏–±–∫—Ä—É—á",
    "–ò–Ω–≥–µ—Ä–º–∞–Ω–ª–∞–Ω–¥–∏—è",
    "–∏–Ω–¥–∏–≤–∏–¥–Ω–æ–µ",
    "–∏–Ω–µ—Ä—Ü–∏–π",
    "–ò–æ–∞–Ω–æ–≤–Ω–∞",
    "–ö–∞–∑–∏–º–∏—Ä–æ–≤",
    "–ö–∞–ª–∏—Ç–∞",
    "–ö–∞–ª–∫–∞",
    "–∫–∞–ª–æ—Ä–∏—á–µ—Å–∫–∏–µ",
    "–ö–∞–Ω—Ç–µ–ª–ª–∏",
    "–ö–∞–ø—É—Ç–∫–∏–Ω–∞",
    "–ö–∞–ø—É—Ç–∫–∏–Ω–æ–π",
    "–∫–∞—Ä—Ç—É—Å–∏–ª–∏–π",
    "–∫–∞—Å–Ω–∞–ø—Ä",
    "–∫–≤–∞–¥—Ä–∞—Ç–∏—á–µ—Å–∫–∞—è",
    "–∫–≤–∞–¥—Ä–∞—Ç–∏—á–µ—Å–∫–æ–µ",
    "–∫–≤–∞–¥—Ä–æ–±–µ—Ä—Å—Ç–≤–æ",
    "–∫–≤–∞–∑–∏",
    "–ö–µ–ª—å–≤–∏–Ω–∞—Ö",
    "–ö–ª–µ—Ä–æ",
    "–∫–Ω—è–∂–∏—Ç—å",
    "–ö–æ–≤–∞—Ä–∏–∞—Ü–∏—è",
    "–∫–æ–≤–∞—Ä–∏–∞—Ü–∏—è",
    "–∫–æ–º–ø–µ—Ç–µ–Ω—Ü–∏–π",
    "–ö–æ–Ω–¥—Ä–∞—Ç—å–µ–≤–∞",
    "–ö–æ–Ω–¥—Ä–∞—Ç—å–µ–≤–æ–π",
    "–∫–æ–Ω–æ–¥–∞",
    "–∫–æ–Ω–æ–¥—ã",
    "–ö–æ–Ω—Ç",
    "–∫–æ—Ä—Ä–µ–ª–∏—Ä–æ–≤–∞–Ω–Ω–æ—Å—Ç—å",
    "–∫–æ—Ä—Ä–µ–ª–∏—Ä–æ–≤–∞–Ω–Ω—ã–µ",
    "–ö–æ—Ä—Ä–µ–ª–∏—Ä–æ–≤–∞–Ω–Ω—ã–º–∏",
    "–∫–æ—Å–æ—Å–∏–º–º–µ—Ç—Ä–∏—á–Ω—ã–π",
    "–∫—Ä–∏–≤–∞—è—Ä–∞—Å—Ç",
    "–∫—Ä–∏–≤–æ—Ö–ª",
    "–∫—Ä–∏–≤–æ—Ö–ª–∞–¥",
    "–ö—Ä–∏–≤–æ—à–∏–ø–Ω–æ",
    "–∫—Ä—É—á–¥–∏–∞–≥—Ä–Ω–∞–ø—Ä",
    "–∫—Ä—É—á–∫—Ä—É–≥",
    "–∫—Ä—É—á–ø—Ä—è–º",
    "–∫—Ä—É—á—Ä–∞–∑—Ä",
    "–∫—Ä—É—á—Å–µ—á–µ–Ω–∏–µ",
    "–ö—É—Ä–Ω–∞–∫–æ–≤–∞",
    "–ª–∞–±–∞",
    "–õ–µ–≤–∏",
    "–ª–µ–≥–∏—Ä–æ–≤–∞–Ω–Ω–æ—Å—Ç—å",
    "–ª–µ—Ç–∏—è",
    "–õ–µ—Ñ–æ—Ä—Ç",
    "–õ–µ—Ñ–æ—Ä—Ç–∞",
    "–õ–µ—Ö",
    "–õ–µ—Ö–∞",
    "–õ–∂–µ–¥–º–∏—Ç—Ä–∏–π",
    "–õ–∂–µ–¥–º–∏—Ç—Ä–∏—è",
    "–õ–∏–ø–∫–∏–Ω–∞",
    "–õ–æ–≥–Ω–æ—Ä–º–∞–ª—å–Ω–æ–µ",
    "–õ–æ–∫—Ç–µ–≤–∞",
    "–õ–æ–º—Ü–æ–≤–∞",
    "–õ–æ–ø—É—Ö–∏–Ω–∞",
    "–õ–æ–ø—É—Ö–∏–Ω–æ–π",
    "–õ–æ—Ç–∞—Ä–∏–Ω–≥–∏—è",
    "–õ—É–Ω—ë–≤–∞",
    "–õ—ã—Å–∞–∫–æ–≤–∞",
    "–õ—ã—Å–∞–∫–æ–≤–æ–π",
    "–õ—é–¥–µ—Ä—Å–∞",
    "–õ—é—Å—Å–∞–∫—É",
    "–õ—è–æ—è–Ω–æ–º",
    "–õ—è—Ö",
    "–ú–∞–∑–µ–ø—ã",
    "–ú–∞–π–µ—Ä–∞",
    "–ú–∞–π–µ—Ä—Å—É",
    "–º–∞–∫—Ä–æ—Å–æ—Ü–∏–æ–ª–æ–≥–∏—è",
    "–ú–∞–∫—Å–æ–∫–æ–≤—Å–∫–∞—è",
    "–º–∞–ª–æ–ø–ª–∞—Å—Ç–∏—á–Ω—ã–µ",
    "–ú–∞–ª—é—Ç–∞",
    "–ú–∞–Ω–∏–ø—É–ª—è—Ç–∏–≤–Ω–æ–µ",
    "–º–∞–Ω–∏–ø—É–ª—è—Ç–∏–≤–Ω–æ–π",
    "–ú–∞—Ä–∏–æ—Ç—Ç—É",
    "–ú–∞—Ä–∫–æ–≤–∞",
    "–ú–∞—Ä—Ç–∏—Ä–æ—Å–æ–≤",
    "–ú–∞—Ä—Ç–∏—Ä–æ—Å–æ–≤–∞",
    "–ú–∞—Ä—Ç–æ–≤",
    "–ú–∞—Å–ª–æ—É",
    "–ú–∞—Ç–∏–Ω–¥—É–∫—Ü–∏—è",
    "–ú–∞—Ç—ã—Ü–∏–Ω",
    "–º–µ–¥–∏–∞",
    "–ú–µ–Ω–µ–ª–∞—è",
    "–ú–µ–Ω—à–∏–∫–æ–≤",
    "–ú–µ—Å–Ω—è–Ω–∫–∏–Ω",
    "–º–µ—Ç–∞—Å—Ç–∞–±–∏–ª—å–Ω–µ–µ",
    "–ú–∏–∫—Ä–æ",
    "–ú–∏–ª–æ—Ä–∞–¥–æ–≤–∏—á",
    "–ú–∏–ª—é–∫–æ–≤",
    "–ú–∏–Ω–∏–Ω",
    "–ú–∏—Ä–∑–æ—è–Ω",
    "–ú–Ω–∏—à–µ–∫",
    "–º–Ω–æ–≥–æ–∫–æ–Ω—Ñ–µ—Å—Å–∏–æ–Ω–∞–ª—å–Ω–∞—è",
    "–º–Ω–æ–≥–æ–º–µ—Ä–Ω–∞",
    "–º–Ω–æ–≥–æ—Ñ–∞–∫—Ç–æ—Ä–Ω–∞",
    "–ú–æ–±–±–∏–Ω–≥",
    "–º–æ–¥–µ—Ä–Ω–∏–∑–∞—Ü–∏–æ–Ω–Ω–æ–º",
    "–º–æ–º–µ–Ω—Ç–Ω–∞—è",
    "–º–æ–º–µ–Ω—Ç–Ω—ã—Ö",
    "–ú–æ–Ω–æ",
    "–ú–æ–Ω–æ–º–∞—Ö",
    "–ú–æ–Ω–æ–º–∞—Ö–∞",
    "–º–æ–Ω–æ–º–µ—Ç—Ä–∏—á–µ—Å–∫–æ–µ",
    "–º–æ–Ω–æ–ø–æ–ª–∏",
    "–ú–æ—Ä–≥–∞–Ω",
    "–ú—É–∞–≤—Ä",
    "–ú—É–∞–≤—Ä–∞",
    "–ú—É–∞–≤—Ä—É",
    "–ú—É–∫–¥–µ–Ω–æ–º",
    "–Ω–∞–ø—Ä—Å–æ—Å—Ç",
    "–ù–∞—Ä—ã—à–∫–∏–Ω–∞",
    "–Ω–µ–¥–≤–æ–π–Ω–∏–∫–æ–≤—ã–π",
    "–Ω–µ–∏–∑–º–µ–Ω—è–µ–º–∞",
    "–ù–µ–π–º–∞–Ω–∞",
    "–ù–µ–∫–æ–º–ø–µ–Ω—Ç–µ–Ω—Ç–Ω–æ—Å—Ç—å",
    "–Ω–µ–∫–æ—Ä—Ä–µ–ª–∏—Ä–æ–≤–∞–Ω–Ω–æ—Å—Ç—å",
    "–Ω–µ–∫–æ—Ä—Ä–µ–ª–∏—Ä–æ–≤–∞–Ω–Ω—ã–µ",
    "–Ω–µ–æ–≥—Ä—Ä–∞—Å—Ç",
    "–Ω–µ–ø–µ—Ä–µ—Å–µ–∫–∞—é—â–∏–º—Å—è",
    "–Ω–µ–ø–µ—Ä–ø–µ–Ω–¥–∏–∫—É–ª—è—Ä–Ω–æ–π",
    "–Ω–µ—Å–æ–≤–º–µ—Å—Ç–Ω—ã",
    "–Ω–µ—Ç–æ–Ω–∫–æ—Å—Ç–µ–Ω–Ω–æ–≥–æ",
    "–Ω–∏–∑–∫–æ—É–≥–ª–µ—Ä–æ–¥–∏—Å—Ç—ã—Ö",
    "–Ω–æ–Ω–≤–∞—Ä–∏–∞–Ω—Ç–Ω–∞—è",
    "–û–±–µ–ª—è",
    "–æ–±—Ä–∞—Ç–Ω–æ—Å–∏–º–º–µ—Ç—Ä–∏—á–Ω—ã–π",
    "–æ–±—Ä—Å–∂–∞—Ç",
    "–û–≥—é—Å—Ç",
    "–û–¥–∏–Ω–∞",
    "–æ—Ä–≥–∞–Ω–∏—á–Ω–∞",
    "–æ—Ä–¥—ã–Ω—Ü–µ–≤",
    "–û—Ä–µ—Ö–æ–≤–∞",
    "–û—Ä—Ç–æ—Ü–µ–Ω—Ç—Ä",
    "–û—Ä—à–∞–Ω–∫–µ",
    "–û—Å–∫–æ–ª—å–¥–∞",
    "–æ—Å—Ç—Ä–æ–≤–µ—Ä—à–∏–Ω–Ω–æ—Å—Ç—å—é",
    "–æ—Ç–∫—Ä–ø—Ä–æ—Ñ",
    "–û—Ç—Ä–µ–ø—å–µ–≤—ã–º",
    "–ü–µ–≥–∞—á–∫–æ–≤–∞",
    "–ü–µ—Ä–µ–ø–ª–∞—Ç–∞",
    "–ø–µ—Ä–µ–ø–æ—Ö–æ—Ä–æ–Ω–∏–ª–∏",
    "–ø–µ—Ä–µ—Ä–µ–∑—ã–≤–∞—é—â–∞—è",
    "–ü–µ—Ä–µ—Ä–µ–∑—ã–≤–∞—é—â–∞—è",
    "–ø–µ—Ä–µ—Ä–µ–∑—ã–≤–∞—é—â–µ–π",
    "–ø–µ—Ä–µ—Ä–µ–∑—ã–≤–∞—é—â–∏—Ö",
    "–ü–µ—Ä–µ—Å–ª–∞–≤–ª–µ",
    "–ü–µ—Ä—É–Ω—É",
    "–ü–∏—Ä—Å–æ–Ω",
    "–ü–ª–∞—Ç–æ–Ω–æ–≤—É",
    "–ü–ª–æ—Å–∫–æ–ø—Ä–æ—Å—Ç—Ä–∞–Ω—Å—Ç–≤–µ–Ω–Ω–∞—è",
    "–ü–ª—é—à–∫–∏–Ω",
    "–ø–æ–≤–¥–µ—Ñ–µ–∫—Ç—ã",
    "–ø–æ–¥–ø–∞–ø–∫–∏",
    "–ü–æ–¥—à–∏–ø–Ω–æ",
    "–ü–æ–∂–∞—Ä—Å–∫–∏–π",
    "–ü–æ–∂–∞—Ä—Å–∫–æ–º—É",
    "–ø–æ–∫—Ä–µ—â—ë–Ω",
    "–ø–æ–ª–∑—É–Ω–Ω—ã–π",
    "–ü–æ–ø—É—Å—Ç–∏—Ç–µ–ª—å—Å–∫–∏–π",
    "–ü–æ—Ä–æ—Ö–Ω–∏",
    "–ü–æ—Ä—Ç—Å–º—É—Ç—Å–∫–∞—è",
    "–ü–æ—Ä—Ç—Å–º—É—Ç—Å–∫–∏–π",
    "–ü–æ—Å–µ–ª—å–µ",
    "–ø–æ—Ç–æ–∫–æ—Å—Ü–µ–ø–ª–µ–Ω–∏–µ",
    "–ü—Ä–∞–∫—Å–µ–æ–ª–æ–≥–∏—á–µ—Å–∫–∞—è",
    "–ø—Ä–∏–≤–µ–¥—É—Ç—Å—è",
    "–ü—É–≥–∞—á—ë–≤",
    "–ü—É—Ä–∏—à–∫–µ–≤–∏—á",
    "—Ä–∞–≤–Ω–æ–≤–µ—Ä–æ—è—Ç–Ω–æ—Å—Ç—å",
    "—Ä–∞–≤–Ω–æ–≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å",
    "—Ä–∞–≤–Ω–æ–≤–æ–∑–º–æ–∂–Ω—ã–º–∏",
    "—Ä–∞–≤–Ω–æ–≤–æ–∑–º–æ–∂–Ω—ã—Ö",
    "—Ä–∞–≤–Ω–æ–æ—Å–Ω—ã—Ö",
    "—Ä–∞–≤–Ω–æ–æ—Ç—Å—Ç–∞—é—â–∏—Ö",
    "—Ä–∞–¥–∏–∫–∞–ª–∏–∑–∞—Ü–∏–∏",
    "–†–∞–¥–∏—â–µ–≤",
    "—Ä–∞–∑–≥—Ä–∞–±–ª—è–ª",
    "—Ä–∞–∑–≥—Ä–æ–º–ª–µ–Ω–∏—è",
    "–†–∞–∑–∏–Ω",
    "—Ä–∞–∑–Ω–æ–∑–µ—Ä–Ω–∏—Å—Ç–æ—Å—Ç—å",
    "—Ä–∞–∑—É–ø—Ä–æ—á–Ω—è—é—Ç—Å—è",
    "—Ä–∞—Å—Ç–¥–µ—Ñ–æ—Ä–º",
    "—Ä–∞—Å—Ç—Å–µ—á–µ–Ω–∏—è",
    "—Ä–µ–∫–∫—É—Ä–µ–Ω—Ç–Ω–æ–π",
    "—Ä–µ–∫—Ä",
    "–†–µ–∫—Ä–∏—Å—Ç–∞–ª–ª–∏–∑–∞—Ü–∏–æ–Ω–Ω—ã–π",
    "—Ä–µ–∫—É—Ä—Ä–µ–Ω—Ç–Ω–æ",
    "—Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π",
    "—Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏—è",
    "—Ä–µ—à–µ–∫",
    "–†–æ–¥–∑—è–Ω–∫–æ",
    "–†–æ–∫–≤–µ–ª–ª–∞",
    "–†–æ–∫–≤–µ–ª–ª—É",
    "–†–æ–º–∞–Ω–æ–≤–∞",
    "–†–æ–º–∞–Ω–æ–≤—ã—Ö",
    "–†–æ–ø—à—É",
    "–†–æ—Å—Ç–æ–≤—Å–∫–æ",
    "–†–æ—Å—å",
    "–†—É–¥–Ω–µ–Ω–∫–æ",
    "–†—é—Ä–∏–∫",
    "–†—é—Ä–∏–∫–∞",
    "–°–∞–º–æ–∞–∫—Ç—É–∞–ª–∏–∑–∞—Ü–∏—è",
    "—Å–≤–∏–Ω–µ—Ü—Å—É—Ä—å–º–∞",
    "—Å–≤–æ–±—ç–Ω–µ—Ä–≥–∏—è",
    "–°–≤—è—Ç–æ–ø–æ–ª–∫",
    "–°–≤—è—Ç–æ–ø–æ–ª–∫–∞",
    "–°–≤—è—Ç–æ–ø–æ–ª–∫—É",
    "–°–µ–º—ë–Ω–æ–≤–∞",
    "—Å–µ–º—ë–Ω–æ–≤—Å–∫–∏–µ",
    "–°–µ–Ω",
    "–°–µ—Ä–≥–∏–µ–≤–∞",
    "–°–µ—Ä–≥–∏–µ–≤—É",
    "—Å–µ—Ä–∏–∞–ª—å–Ω—ã–µ",
    "–°–µ—Ä–∏–∞–ª—å–Ω—ã–µ",
    "—Å–∂–∞—Ç—ç–∫—Å–ø",
    "—Å–∏–≥–º",
    "–°–∏–º–µ–Ω—Å",
    "—Å–∏–º–º–µ—Ç—Ä",
    "–°–∏–Ω–µ—É—Å",
    "—Å–∏—Å—Ç–µ–º–Ω–∞",
    "–°–∫–∞–≤—Ä–æ–Ω—Å–∫–æ–π",
    "—Å–∫–æ—à–µ–Ω–Ω–æ—Å—Ç–∏",
    "–°–∫—Ä–∏–≤—ã–µ",
    "–°–∫—É—Ä–∞—Ç–æ–≤",
    "–°–ª–∞–≤—è–Ω–æ",
    "—Å–ª–æ–∂–Ω–æ–ª–µ–≥–∏—Ä–æ–≤–∞–Ω–Ω—ã—Ö",
    "—Å–ª–æ–∂–Ω–æ–æ—Ä–≥–∞–Ω–∏–∑–æ–≤–∞–Ω–Ω—ã–π",
    "—Å–º–æ—Ç—Ä–∏–ª–∫–µ",
    "—Å–æ–¥–µ—Ä–∂–∞–Ω–∏—è—Ö",
    "–°–æ—Ä–æ—Å–∞",
    "—Å–æ—Ä—Ä–µ",
    "—Å–ø–µ—Ü–æ–ø–µ—Ä–∞—Ü–∏—è",
    "—Å–ø–ª–æ—à–Ω–æ—Å—Ç–∏",
    "–°–ø–æ—Ä—Ç–ª–æ—Ç–æ",
    "–°—Ä–µ–¥–Ω–µ–∫–≤–∞–¥—Ä–∞—Ç–∏—á–µ—Å–∫–∞—è",
    "—Å—Ä–µ–¥–Ω–µ–∫–≤–∞–¥—Ä–∞—Ç–∏—á–µ—Å–∫–æ–µ",
    "—Å—Ä–µ–¥–Ω–µ—É–≥–ª–µ—Ä–æ–¥–∏—Å—Ç—ã—Ö",
    "—Å—Ç–∞–Ω–¥–æ–±—Ä",
    "—Å—Ç–µ—Ä–µ–æ—Ç–∏–ø–∏–∑–∞—Ü–∏—è",
    "–°—Ç–æ–ª–±–æ–≤–æ",
    "–°—Ç–æ–ª—ã–ø–∏–Ω–∞",
    "–°—Ç—É–¥–Ω–∏–∫–æ–≤",
    "–°—Ç—É–¥–Ω–∏–∫–æ–≤–∞",
    "–°—Ç—é–∞—Ä—Ç–∞",
    "—Å—É–±–∑—ë—Ä–µ–Ω",
    "—Å—É–±–∑—ë—Ä–Ω–∞",
    "–°—É–≤–æ—Ä–æ–≤",
    "–°—É–≤–æ—Ä–æ–≤–∞",
    "–°—É–≤–æ—Ä–æ–≤—É",
    "–°—É–¥–µ–±–Ω–∏–∫",
    "—Å—É–ø–µ—Ä–ª–µ–Ω—å",
    "—Å—Ñ–µ—Ä–æ–∏–¥–∏–∑–∏—Ä—É—é—â–∏–π",
    "–¢–í–∏",
    "—Ç–µ—Ç—Ä–∞–≥–æ–Ω–∞–ª—å–Ω–æ—Å—Ç–∏",
    "–¢–∏–º—É—á–∏–Ω",
    "–¢–∫–∞—á–µ–Ω–∫–æ",
    "—Ç–æ–ª—Å—Ç–æ—Å—Ç–µ–Ω–Ω–æ—Å—Ç–∏",
    "—Ç–æ–Ω–∫–æ–ø–ª–∞—Å—Ç–∏—á–Ω–∞—è",
    "—Ç–æ–Ω–∫–æ—Å—Ç–µ–Ω",
    "—Ç–æ–Ω–∫–æ—Å—Ç–µ–Ω–Ω–æ—Å—Ç–∏",
    "—Ç–æ—á–¥–µ—Ñ–µ–∫—Ç—ã",
    "–¢—Ä–µ—Ç—å–µ–∏—é–Ω—å—Å–∫–∞—è",
    "—Ç—Ä–µ—Ö—Å—Ç–µ—Ä–∂–Ω–µ–≤–æ–π",
    "–¢—Ä—É–±–µ—Ü–∫–æ–π",
    "–¢—Ä—É–≤–æ—Ä",
    "—Ç—Ä—ë—Ö–≥–æ–ª–æ–≤—ã–º",
    "–¢—Ä—ë—Ö—Å—Ç–µ—Ä–∂–Ω–µ–≤–∞—è",
    "–¢—É—à–∏–Ω–æ",
    "—É–¥–∞—Ä–∏–∑–≥–∏–±",
    "—É–ª–æ–∂–∏—Ç–µ–ª—å–Ω—É—é",
    "—É–ª—ã–±–∞—à–∫–∞",
    "—É—Å—Ä–µ–¥–Ω—ë–Ω–Ω–Ω—ã–µ",
    "—É—Å—Ç–∞–ª–æ—Å—Ç–ø–æ–≤—Ä",
    "—É—Å—Ç—Ñ–æ–∫—É—Å",
    "–§–∞–ª–µ—Å–∞",
    "–§–∞—Ä—Ä–∏",
    "–§–∞—É—Å—Ç–∞",
    "–§–µ–ª–ª–µ—Ä",
    "–§–µ–æ–∫—Ç–∏—Å–æ–≤–∞",
    "–§–µ–æ–∫—Ç–∏—Å–æ–≤–æ–π",
    "–§–µ—Ä–º–µ–Ω–Ω–∞—è",
    "—Ñ–µ—Ä–º–µ–Ω–Ω–æ–π",
    "—Ñ–µ—Ä–º–µ–Ω–Ω—ã–µ",
    "—Ñ–µ—Ä—Ä–∏—Ç–æ",
    "–§–∏–±–±–æ–Ω–∞—á–∏",
    "–§—Ä–∞–Ω–∫–µ–Ω—à—Ç–µ–π–Ω–∞",
    "–§—Ä–µ–π–¥",
    "–§—Ä–µ–π–¥—É",
    "–§—Ä–æ–º–º",
    "—Ö–ª–µ–±–æ–ø–∞—à—Ü–∞—Ö",
    "—Ö–æ–ª–æ–¥–Ω–æ–ª–æ–º–∫–æ—Å—Ç–∏",
    "–•–æ–ø—Ñ–∞",
    "–¶–∞—Ä–∏—Ü—ã–Ω",
    "—Ü–µ–º–µ–Ω—Ç–∏—Ç–Ω–æ–π",
    "—Ü–µ–Ω—Ç—Ä—Ç—è–∂",
    "—Ü–µ—Ä–µ–º–æ–Ω–∏–∞–ª—å–Ω–æ",
    "–ß–µ–≤—ã",
    "–ß–µ—Ä–Ω–æ–≤",
    "–ß–µ—Ä–Ω–æ–≤–∞",
    "—á–µ—Ç—ã—Ä–µ—Ö–∑–≤–µ–Ω–Ω—ã–π",
    "–ß–∏–Ω–≥–∏—Å—Ö–∞–Ω",
    "–ß—É–¥–æ–≤–æ–º",
    "–®–µ–∏–Ω",
    "–®–µ–∏–Ω—É",
    "–®–µ—Ö–ª–æ–≤–∏—Ç—ã–π",
    "—à—Ç—Ä–∏—Ö—É—é—Ç—Å—è",
    "–®—É–≤–∞–ª–æ–≤",
    "—ã–º",
    "—ã—Ö",
    "—ç–≤—Ç",
    "–≠–≤—Ç–µ–∫—Ç–æ–∏–¥–Ω–∞—è",
    "—ç–≤—Ç–µ–∫—Ç–æ–∏–¥–Ω—ã–µ",
    "–≠–¥–µ–ª—å—à—Ç–µ–π–Ω–∞",
    "—ç–∫—Å—Ç—Ä",
    "—ç–ª–µ–∫—Ç—Ä–æ",
    "–≠–ª–µ–∫—Ç—Ä–æ–ø—Ä–æ–≤–æ–¥–∏–º–æ—Å—Ç—å",
    "—ç–ª–µ–∫—Ç—Ä–æ—à–ª–∞–∫–æ–≤–∞—è",
    "—ç–º–ø–∞—Ç–∏–∏",
    "—ç–ø—é—Ä–∞—Ç–∞—É",
    "–Ø—Ä–æ–ø–æ–ª–∫",
    "–Ø—Å–ø–µ—Ä—Å",
]

ignore_patterns = [
    '^[A-Z]{2,}$',
    '^[\u0400-\u042F]{2,}$',
]
